- platform: template
  sensors:
    shelly_current_consumption:
        friendly_name: Current Power
        entity_id: sensor.time
        unit_of_measurement: W
        value_template: >
          {% set ns = namespace(states=[]) %}
          {% for s in states.sensor %}
            {% if s.object_id.startswith('shelly_sh') and s.object_id.endswith('_current_consumption') %}
              {% set ns.states = ns.states + [ s.state | float ] %}
            {% endif %}
          {% endfor %}
          {{ ns.states | sum | round(2) }}		
